# Generated by Django 5.1.2 on 2024-10-27 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("date_added", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TextMeta",
            fields=[
                ("text_id", models.AutoField(primary_key=True, serialize=False)),
                ("hsk_level", models.IntegerField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chinese_hsk.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextFull",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_full", models.TextField()),
                (
                    "text_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chinese_hsk.textmeta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextParagraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_number", models.IntegerField()),
                ("p_text", models.TextField()),
                (
                    "text_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chinese_hsk.textmeta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_name", models.CharField(max_length=255)),
                (
                    "text_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chinese_hsk.textmeta",
                    ),
                ),
            ],
        ),
    ]
